---
title: "**Actividad 331**"
author: "dgonzalez80"
date: " "
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---

# **Descripción**

Construir un  **poster** para cada uno de los modelos asignados que contenga sus principales caracteristicas

##### * Origen de la distribución

##### * Características principales : f(x), F(x), E[X], V[X], ....

##### * Ejemplo con solución y sintaxis en R

##### * Aplicaciones en el campo de las ingeniería, ciencias, economía, salud...

##### * Relaciones entre distribuciones univariadas.  [(Artículo)](http://www.stat.rice.edu/~dobelman/courses/texts/leemis.distributions.2008amstat.pdf)

##### * Referencias bibliográficas 

<br/><br/><br/>

# **Conformación grupos**

<br/><br/>


|Grupo       | Distribuciones                        |
|:----------:|:--------------------------------------|
| Grupo 1    | distribución 1 : nomal                |
|            | distribución 2 : geométrica           |
|            |                                       |
| Grupo 2    | distribución 1 : exponencial          |
|            | distribución 2 : binomial             |
|            |                                       |
| Grupo 3    | distribución 1 : lognormal            |
|            | distribución 2 : Poisson              |
|            |                                       |
| Grupo 4    | distribución 1 : t-Student            |
|            | distribución 2 : binomial negativa    |
|            |                                       |
| Grupo 5    | distribución 1 : gamma                |
|            | distribución 2 : hipergeometrica      |
|            |                                       |
| Grupo 6    | distribución 1 : beta                 |
|            | distribución 2 : Poisson              |
|            |                                       |
| Grupo 7    | distribución 1 : Gumbel               |
|            | distribución 2 : binomial negativa    |
|            |                                       |
| Grupo 8    | distribución 1 :  Weibull             |
|            | distribución 2 :  geométrica          |
|            |                                       |
| Grupo 9    | distribución 1 : F                    |
|            | distribución 2 : hipergeométrica      |
|            |                                       |
| Grupo 10   | distribución 1 : ji-cuadrado          |
|            | distribución 2 : hipergeométrica      |
|            |                                       |
| Grupo 11   | distribución 1 : normal               |
|            | distribución 2 : binomial             |
|            |                                       |
| Grupo 12   |  distribución 1 : geométrica          |
|            |  distribución 2 : uniforme continua   |
|            |                                       |
| Grupo 13   |  distribución 1 : Poisson             |
|            |  distribución 2 : exponencial         |
|            |                                       |
| Grupo 14  |  distribución 1 : geométrica           |
|            | distribución 2 : Cauchy               |
|            |                                       |
| Grupo 15   |  distribución 1 : binomial negativa   |
|            |  distribución 2 : lognormal           |
|            |                                       |
| Grupo 16   |  distribución 1 : hipergeométrica     |
|            |  distribución 2 : gamma               |
|            |                                       |
| Grupo17    |  distribución 1 : normal              |
|            |  distribución 2 : binomial            |
|            |  |


<br/><br/><br/>

# **Videos PyE 2020-2**

<br/><br/>

## **Distribución uniforme**

<iframe width="560" height="315" src="https://www.youtube.com/embed/6iDQHdqAwyQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/>

<iframe width="560" height="315" src="https://www.youtube.com/embed/e4U3YX4fXrQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución normal**

<iframe width="560" height="315" src="https://www.youtube.com/embed/NlD5jbLc2-A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/>

<iframe width="560" height="315" src="https://www.youtube.com/embed/llhl115ltbY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

### **Distribución exponencial**

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZPxY9sbClJo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución Lognormal**

<iframe width="560" height="315" src="https://www.youtube.com/embed/wK7q-XJnsN4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/>

<iframe width="560" height="315" src="https://www.youtube.com/embed/XtACgL4eVvk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución beta**

<iframe width="560" height="315" src="https://www.youtube.com/embed/KBiu4mu1Wng" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución Gumbel**

<iframe width="560" height="315" src="https://www.youtube.com/embed/2NEw7SZeNZU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución Weibull**

<iframe width="560" height="315" src="https://www.youtube.com/embed/FI5zZYr1p7s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/>

## **Distribución t-Student**

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZYYDhGXOcX8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución F**

<iframe width="560" height="315" src="https://www.youtube.com/embed/rC8C_e8L1xc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución geométrica**

<iframe width="560" height="315" src="https://www.youtube.com/embed/u5lLIlxknOk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/>

<iframe width="560" height="315" src="https://www.youtube.com/embed/oiGEQTRfQLo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución de Poisson**

<iframe width="560" height="315" src="https://www.youtube.com/embed/6ZFx954dOcM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución  hipergeométrica**

<iframe width="560" height="315" src="https://www.youtube.com/embed/pKjW3jtR7YI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución binomial**

<iframe width="560" height="315" src="https://www.youtube.com/embed/VcUxRQ-fvWo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/>

<iframe width="560" height="315" src="https://www.youtube.com/embed/_SJ9AhKOGVQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/>

<iframe width="560" height="315" src="https://www.youtube.com/embed/TrimcQJFThU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribución binomial negativa**

<iframe width="560" height="315" src="https://www.youtube.com/embed/vm1V9XZVC_Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/>

<iframe width="560" height="315" src="https://www.youtube.com/embed/1WEEGkkIcCE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/><br/><br/><br/>

## **Distribuciones binomial y uniforme**

<iframe width="560" height="315" src="https://www.youtube.com/embed/Wub6Rhacj3g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


<br/><br/><br/><br/>

