---
title: "**Guía Trabajo final**"
author: "dgonzalez"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# colores
c0="#0DA5A6" # VERDE CLARO
c1="#E77C00" # NARANJA
c2="#6666FF" # AZUL  
c3="#4CBFBA" # VERDE CLARO  
c4="#E09600" # AMARILLO  
c5="#BC2B6A" # MORADO  

```


Los estudiantes deberán realizar un proyecto que les permita poner en práctica los conocimientos adquiridos en el curso de  Probabilidad y Estadística.

<br/><br/><br/>

## **Objetivos** 

+ Contribuir a la formación integral, al trabajo en equipo y la interrelación de conocimientos de Estadística alrededor de un problema específico.

+ Permitir los estudiantes detectar situaciones en las cuales pueda aplicar las técnicas Estadísticas estudiadas.

+ Desarrollar destrezas en el análisis estadístico y la presentación de informes estadísticos. 

<br/><br/><br/>

## **Temática** 

En grupos de hasta de tres estudiantes deberán desarrollar un trabajo que corresponda a un problema de  interés para el  grupo, que permita la aplicación de la Estadística en un tema específico. 

El producto de este trabajo deberá ser entregado en una infografía junto a un resumen  

<br/><br/><br/>

## **Requisitos** 

+ Máximo tres, mínimo de dos integrantes. No se permiten trabajos individuales.

+ Seleccionar un problema de interés propio para el grupo que  permita la aplicación de los conocimientos de estadística vistos en el curso. El tema propuesto deberá contar con el visto bueno del profesor.

+  El contenido de la infografía deberá utilizar por lo menos 6 resultados producto de la inferencia estadística (intervalos de confianza o pruebas de hipótesis) que respalden los resultados presentados

+ Al final los estudiantes deberán realizar una presentación del trabajo y de los principales hallazgos. Cada grupo contará con un tiempo de 5 minutos para la presentación de los resultados.

<br/><br/><br/>

## **Fechas** 

Entrega de informes: 

+ Primera entrega:
  + **Documento pdf** :Tema, objetivos, información y planteamiento de las inferencias a realizar
  + Fecha: octubre 31 de 2021 
  
	
+ Entrega del informe final y presentación:
  + **Infografía** en formato pdf o png y **resumen.pdf** tipo artículo
  + Fecha: noviembre 24 de 2021
  + El trabajo será socializado en un blog del curso
  
<br/><br/><br/>

## **Referencias** 

+ Metodología de la investigación . Hernandez Sampieri Roberto. Segunda edición. Mc Graw-Hill
+ Investigación de Mercados. Naresh K. Malhotra. Quinta Edición. Pearson.

Herramientas sugeridas :  [Canva](https://www.canva.com/es_co/herramientas/infographic-maker-v1/?utm_source=google_sem&utm_medium=cpc&utm_campaign=co_es_all_pro_rev_conversion_infographic_em_exp&utm_term=co_es_all_pro_rev_conversion_Infographic-Maker_em_exp&gclid=CjwKCAjwkvWKBhB4EiwA-GHjFtDDvq5SNOCudFscSvOINGSVSe0cBj2ZRKr-j3DL_nulbF4UsQvIyxoCFukQAvD_BwE&gclsrc=aw.ds),  [Geneally](https://genial.ly/), [Mural](https://www.mural.co/), [Piktochart](https://piktochart.com/), [Visual](https://visual.ly/)


<br/><br/><br/>

## **Grupos**

<br/>

### **Curso 300MAE005 B**

|**Grupo**  | **Nombres**             |
|:---------:|:------------------------|
|Grupo 1    | José David Benavides    | 
|           |Erika Burckhardt         |
|           |Daniel Sinisterra        |
|Grupo 2    | Stephany Rodríguez      |
|           |Cristian Quintero        |
|           |Juan Esteban Espinosa    |
|Grupo 3    |Juan Felipe Rojas        |
|           |Camilo Rios              |
|           |Juan Daniel Lopez        |
|Grupo 4    | Isabella Bonilla        |
|           |Fabio Prado              |
|           |Juan Stevan Marmolejo    |
|Grupo 5    |Daniela Escobar          |
|           |Juan Castiblanco         | 
|           |Evelyn Tobar             |
|Grupo: 6   | Dayani Molina           | 
|           |Sebastián Mesa           |
|           |Daniel Palacios          |
|Grupo 7    |Luis Mendoza             |
|           |Santiago Torres          |
|           |María José Suarez        |
|Grupo 8    |Estaban Quintero         |
|           |Juan José Soto           |
|           |Sebastian Portocarrero   |
|Grupo 9    | Jorge estaban Guevara   | 
|           |Miguel Fernando Ricardo  | 
|           |Sebastian sierra Lezama  |
|Grupo 10   | Nicolas Lozano          | 
|           |Tomas Moreno             |


<br/><br/><br/>

### **Curso 300MAE005 E**

|**Grupo**  | **Nombres**            |
|:---------:|:-----------------------|
|Grupo 1|Ana María Azcarate          |
|       |Ana María Rubio             |
|Grupo 2| Juan Camilo Jimenez        | 
|       |Juan José Zuleta            |
|Grupo 3|Adrián Timana               |  
|       |Nicolás Bolaños             |
|Grupo 4|Jose Olaya                  |
|       |Daniel Moncaleano           |
|Grupo 5|Alejandra Aponza            | 
|       |Santiago Ruiz               |
|Grupo 6|Santiago García             |
|       |Daniel Zambrano             |
|Grupo 7|Juan Fernando Viteri        | 
|       | Juan José lerma            |
|Grupo 8|Luis Rosero                 |
|       |David Velandia              |
|Grupo 9|Daniela Espinosa            |
|       | Gabriel la Troncoso        |