---
title: "Introducción a inferencia estadística"
author: "dgonzalez"
subtitle: "Modulo 4- Unidad 4.1" 
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# colores
c0="#0DA5A6" # VERDE CLARO
c1="#E77C00" # NARANJA
c2="#6666FF" # AZUL  
c3="#4CBFBA" # VERDE CLARO  
c4="#E09600" # AMARILLO  
c5="#BC2B6A" # MORADO  

```



## **Guía de aprendizaje 4.1**

<div class="container-wrapper-genially" style="position: relative; min-height: 400px; max-width: 100%;"><video class="loader-genially" autoplay="autoplay" loop="loop" playsinline="playsInline" muted="muted" style="position: absolute;top: 45%;left: 50%;transform: translate(-50%, -50%);width: 80px;height: 80px;margin-bottom: 10%"><source src="https://static.genial.ly/resources/panel-loader-low.mp4" type="video/mp4" />Your browser does not support the video tag.</video><div id="5f1f835fc43a880d757f9161" class="genially-embed" style="margin: 0px auto; position: relative; height: auto; width: 100%;"></div></div><script>(function (d) { var js, id = "genially-embed-js", ref = d.getElementsByTagName("script")[0]; if (d.getElementById(id)) { return; } js = d.createElement("script"); js.id = id; js.async = true; js.src = "https://view.genial.ly/static/embed/embed.js"; ref.parentNode.insertBefore(js, ref); }(document));</script>

<br/><br/>

<br/><br/>

## **1. Introducción**

La inferencia estadística permite generalizar lo hallado en una muestra a toda la población. Para realizar este proceso contamos con dos opciones: Estimación y las Pruebas de hipótesis. El fundamento de estos procesos está relacionado con varios conceptos que se describen y se discuten en esta unidad. En algunos casos serán apoyados con procesos de simulación que permitirán la verificación de cada uno de ellos. \\
 
Dentro de estos conceptos se destacan: población, muestra, censo, muestreo, parámetro, estimador, tamaño de muestra, tipo de muestreo, métodos de estimación de momentos, método de estimación de máxima verosimilitud, propiedades de estimadores como son insesgadez, eficiencia, consistencia, teorema central del limite, media muestral, proporción muestral, varianza muestral, modelos de probabilidad normal, t-Student, $\chi^{2}$ o ji-cuadrado y F.

<br/><br/>

## **2. Objetivos de la unidad**

Al finalizar esta unidad el estudiante estará en capacidad de RECONOCER los elementos, conceptos y propiedades que intervienen en la inferencia estadística, de tal manera que pueda INFERIR de manera adecuada los resultados obtenidos para la toma de decisiones informadas

<br/><br/>

## **3. Duración**

La presente  unidad será desarrollada durante la comprendida entre 21 y el 25 de Abril .    
Ademas del material suministrado  contaran con el acompañamiento del profesor en dos sesiones (Miércoles y Viernes) y de manera asincrónica con  foro de actividades académicas. Los entegables para esta unidad podrán enviarse a través de la plataforma Blackboard hasta el  25 de Abril.

Para alcanzar los objetivos planteados se propone realizar las siguientes actividades333333

<br/><br/>

## **4. Cronograma de trabajo**


|Actividad           | Descripción                    | 
|:-------------------|:-----------------------------  |
|**Actividad411**        | Construya un mapa mental con que contenga el siguiente grupo de palabras : **población, parámetro, censo, muestra, muestreo, muestreo probabilistico, muestreo no probabilistico, muestreo aleatorio simple, muestreo aleatorio estratificado, puestreo por conglomerados, puestreo por juicio, muestreo por conveniciencia, muestreo bola de nieve, estimador puntual, estimador insesgado, estimador consistente, estimador eficiente, estimación por intervalos de confianza, pruebas de hipotesis** |
|Trabajo  pareja |    |
|Recursos | [Tablero realizado por 300MAE005 A 2020-2](https://padlet.com/dgonzalez80/lijxz9p7nvz5mm2q)|
|Fecha    | octubre 10  |
|Hora     | 23:59     |
|**Actividad412**   | Verifique el cumplimiento del **Teorema Central del Limite** para cada uno de los modelos asignados en la actividad 331 |
|Trabajo individual|   |
|Fecha    | octubre 10  |
|Hora     | 23:59     |

<br/><br/>

## **5. Criterios de evaluación**

* Reconoce los modelos especiales asociados a contextos  y problemas reales

* Utiliza las herramientas estadística apropiadas en el calculo de probabilidades en la solución de problemas en contexto

* Utiliza herramientas computacionales que le permita  la solución de problemas en contexto a través de la simulación


<br/><br/>

## **6. Entregables** 
|              |                  |                                         |
|:-------------|:-----------------|:----------------------------------------|
|Entregable 1  | Actividad411.pdf |  mapa mental                            |
|Entregable 2: | Actividad412.pdf | verificación teorema central del límite |


Los entregables completos y enviados dentro de los tiempos establecidos  otorgarán 10 puntos en cada caso, para un  total de 20 puntos. 

<br/><br/><br/><br/>

## **7. Presentaciones**



# **Recursos**



## Video 

<iframe width="560" height="315" src="https://www.youtube.com/embed/jbrnCa3jq0Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


