---
title: "**Conceptos básicos y enfoques de probabilidad**"
author: "dgonzalez"
subtitle: "**Modulo 2- Unidad 2.1**" 
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# colores
c0="#0DA5A6" # VERDE CLARO
c1="#E77C00" # NARANJA
c2="#6666FF" # AZUL  
c3="#4CBFBA" # VERDE CLARO  
c4="#E09600" # AMARILLO  
c5="#BC2B6A" # MORADO  

```

 <span style="color:#E77C00">**En construcción**</span>

## **Guía de aprendizaje 2.1**

<div class="container-wrapper-genially" style="position: relative; min-height: 400px; max-width: 100%;"><video class="loader-genially" autoplay="autoplay" loop="loop" playsinline="playsInline" muted="muted" style="position: absolute;top: 45%;left: 50%;transform: translate(-50%, -50%);width: 80px;height: 80px;margin-bottom: 10%"><source src="https://static.genial.ly/resources/panel-loader-low.mp4" type="video/mp4" />Your browser does not support the video tag.</video><div id="5f4c855734dcc71ce637fbe4" class="genially-embed" style="margin: 0px auto; position: relative; height: auto; width: 100%;"></div></div><script>(function (d) { var js, id = "genially-embed-js", ref = d.getElementsByTagName("script")[0]; if (d.getElementById(id)) { return; } js = d.createElement("script"); js.id = id; js.async = true; js.src = "https://view.genial.ly/static/embed/embed.js"; ref.parentNode.insertBefore(js, ref); }(document));</script>

<br/><br/>

<br/><br/>

## **1. Introducción**

El concepto de probabilidad constituye uno de los  pilares de la estadística que permiten la construcción de  conceptos posteriores como el de  **Variable Aleatoria** e **Inferencia Estadística**. Se parte de  los  conceptos básicos para lo cual se requiere revisar los temas de teoría de  conjuntos y técnicas de conteo del **Módulo 0** (**Unidad 0.2**). 

En esta unidad se consideran los conceptos básicos de probabilidad, los axiomas que la rigen y los diferentes enfoques para su calculo.

<br/><br/>

## **2. Objetivos de la unidad**

Al finalizar la  unidad el estudiante estará en capacidad de DESARROLLAR el pensamiento probabilístico mediante el calculo e interpretación de probabilidades mediante la  comprensión de los CONCEPTOS BÁSICOS, los diferentes ENFOQUES y TIPOS de probabilidad  que le ayuden a cuantificar el riesgo para la toma de decisiones.

<br/><br/>

## **3. Duración**

La presente  unidad será desarrollada durante la  cuarta semana del semestre (18 al 23 de agosto  de 2021). Ademas del material suministrado  contaran con el acompañamiento del profesor en tres sesiones (Lunes, Miércoles y Viernes) y de manera asincrónica con  foro de actividades académicas. Los entregables para esta unidad podrán enviarse a través de la plataforma Brightspace hasta el  23 de agosto.

Para alcanzar los objetivos planteados se propone realizar las siguientes actividades

<br/><br/>

## **4. Cronograma de trabajo**


|Actividad      | Descripción                    | 
|:--------------|:-----------------------------  |
| Actividad 201 |[**Taller201**](https://github.com/dgonzalez80/presentacionespye.io/blob/main/Taller_201.pdf).  Resuelva las preguntas del siguiente  taller y entregue su solución  en formato **pdf**  en el enlace correspondiente de Brightspace.|
|Fecha  |  23 de agosto de 2021 |
|Hora   |  23:59 hora local     |
|||


## **5. Criterios de evaluación**

El **taller201** de la unidad 2.1 recoge los elementos estudiados y por tanto  tiene objetivo la revisión de los principales conceptos tratados.

+ Reconocer los principales conceptos de  probabilidad y su efecto sobre la toma de decisiones informadas.

+ Reconocer e identificar los diferentes tipos de probabilidad  y sus respectivas interpretación.
	
	
<br/><br/>

## **6. Entregables** 

| Entregable |  Descripción                    |
|:--------------|:-----------------------------|
| Actividad201    | Actividad201.pdf : Solucionario taller 201 | 
| Fecha           |Martes  23 de agosto de 2021 | 
|Hora límite      | 23:59  hora  local |
 
<br/><br/><br/><br/>

## **7. Presentaciones**


